### ISSUE TITLE
File uploaded as binaryData

### ISSUE THREAD

**Issue by Rajiv-mar121** [adobe/S3Mock#1133]
Hi Arne,

I am able to connect to S3Mock APIs using postman and AWS SDK but I am facing a problem while uploading file into S3 bucket I can see file created in root folder as binary data as filename.
![image](https://github.com/adobe/S3Mock/assets/20912676/3114a87c-8a31-42cd-8b6f-327616c52d05)

In windows it looks like this:
![image](https://github.com/adobe/S3Mock/assets/20912676/b1fd919d-fe8e-443d-b9b7-b76deb0a08f3)

How can I upload multiple files inside same s3 bucket ? 
I checked documentation (https://github.com/adobe/S3Mock#objects) and found it will always save as binaryData as fileName.

Our requirement is to upload file in s3Mock as exact file name instead of binaryData How can I achieve this?

Regards,
Rajiv

**Comment by afranken** [comment]
Rajiv,
It’s just the internal representation.
Why would it be necessary to use the actual object keys? Storing the objects locally with the objectname presents a lot of challenges due to encoding etc.
What’s your use-case? Why are you looking at the local data? This is just meant to be used for debugging.
 
S3Mock is meant to be used to test applications in a reliable way that use S3 for persistence, and you are always using the API from your application.
 
Look at:
https://github.com/adobe/S3Mock#objects
/<root-folder>/<bucket-name>/<uuid>/binaryData
This is the format. 
Every object gets its own uuid.
 
Just use a loop and upload the same file 10 times as small1.csv, small2.csv, small3.csv, …

the file system will look like this:
/<root-folder>/my-bucket/uuid-1/binaryData
/<root-folder>/my-bucket/uuid-2/binaryData
/<root-folder>/my-bucket/uuid-3/binaryData

Cheers,
Arne

**Comment by Rajiv-mar121** [comment]
Ok Thanks for clarification @afranken
