### ISSUE TITLE
Build error when omitting test as dependency scope

### ISSUE THREAD

**Issue by tuptaker** [adobe/S3Mock#114]
I'm trying to use S3 mock in a spring boot application that uses TLS. I want to start it programmatically and so I've included this in my pom.xml per the readme:

```
<dependency>
  <groupId>com.adobe.testing</groupId>
  <artifactId>s3mock</artifactId>
  <version>...</version>
</dependency>
```
But when I start the application, I'm getting a "ConnectorStartFailedException" with the message "Connector configured to listen on port 8443 failed to start."

Anyone know how I might address this? Is s3mock starting a mock server on the same port 8443 as my application?

**Comment by agudian** [comment]
Hmm, perhaps both spring apps try loading their settings from the same application.properties? You could try to pass the port configs when starting the mock programmatically.

**Comment by tuptaker** [comment]
Hey @agudian , thanks for the response. I've been trying to pass the port config in through maven but I must be doing it wrong since I'm still seeing the issue. I'm passing it in like this -Ds3mock.port_https=9191, but I suppose that is not correct. Alternatively, how might I define the port for s3mock through application.yml?

**Comment by afranken** [comment]
S3Mock 2.2.0 was just released that now includes support for [TestContainers](https://www.testcontainers.org/).
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.

Using S3MockApplication directly or through one of the unit test modules will always have the risk of breaking because of dependencies that are pulled in by the application that is being tested, and auto configration that is added through Spring Boot updates in the S3Mock.

Using Docker in your tests will insulate both applications dependencies and application life cycles.
