### ISSUE TITLE
[Bug] PutObjectLegalHold and PutObjectRetention changes underlying S3 file

### ISSUE THREAD

**Issue by jchou886** [adobe/S3Mock#157]
Calling PutObjectLegalHold and PutObjectRetention changes underlying S3 file for dockerized s3 mock.

Steps to reproduce:
1. Put any object in S3.
2. Call PutObjectRetention or PutObjectLegalHold on the object.
3. The contents of the object changes to the xml of the object retention request or legal hold request.

**Comment by agudian** [comment]
I‘m very sure we haven’t implemented that, yet, and the requests are being treated as normal PUT requests...

Would you be open for contributing that feature?

**Comment by afranken** [comment]
See #213
First, the S3Movk should not accept these requests, so that the local storage is not overwritten. 

Then, a new handler method could be implemented that handles the requests mentioned here. 
Then, several other handler methods that can modify / delete objects must respect the legal hold / object retention.

**Comment by afranken** [comment]
Half of this is implemented, Retention is next.

**Comment by afranken** [comment]
Took longer than expected, but we can finally close this issue. :)

Just released `2.6.0` adding support to handle these requests.
