### ISSUE TITLE
Exclude DataSourceAutoConfiguration.class in S3MockApplication

### ISSUE THREAD

**Issue by alvaro-nogueira** [adobe/S3Mock#216]
In my application I have to manually config the DataSources, so when I call S3MockApplication.start() in my tests it tries to autoconfigure the datasources and that gives me an error.

Is possible to exclude DataSourceAutoConfiguration.class in S3MockApplication?

**Comment by agudian** [comment]
Yes, sure. Would you open a PR for that, then you can directly test it against your app?

**Comment by afranken** [comment]
S3Mock 2.2.0 was just released that now includes support for [TestContainers](https://www.testcontainers.org/).
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.

Using S3MockApplication directly or through one of the unit test modules will always have the risk of breaking because of dependencies that are pulled in by the application that is being tested, and auto configration that is added through Spring Boot updates in the S3Mock.

Using Docker in your tests will insulate both applications dependencies and application life cycles.
