### ISSUE TITLE
To download files locally from Docker S3mock gives an error 

### ISSUE THREAD

**Issue by AnushaErrabelli** [adobe/S3Mock#242]
I'm using docker for S3mock but I have an application running locally, when I upload the files it doesn't complain but when I'm downloading the files it's giving me https://s3mock:9090/test-files but my files are available at http://localhost:9090/test-files is there any way I can modify the request?

**Comment by AnushaErrabelli** [comment]
Error details:
      Failed to find a DNS-record for the resource at

**Comment by ChaithanyaGK** [comment]
@AnushaErrabelli Thanks for reporting.

It looks like the client is trying to connect to HTTPS end-point and the default s3mock HTTPS port is `9191`. If you are intended to use HTTPS then, 
1. Configure the client to use the end-point `https://localhost:9191`
2. Expose `9191` port in your docker-compose.

Or if you want to stick to HTTP then,
1. Configure the client to use the end-point `http://localhost:9090`

**Comment by AnushaErrabelli** [comment]
@ChaithanyaGK Thank you for the reply! Initially I thought of not changing the actual S3 client flow but it seems it's the only way it can be done!

**Comment by afranken** [comment]
@AnushaErrabelli is this question resolved then? :)

**Comment by danieler1981** [comment]
I'm try to download a file this command:
`AWS_ACCESS_KEY_ID=username AWS_SECRET_ACCESS_KEY=password aws --endpoint-url=http://localhost:9090 s3  cp s3://mybucket/a/b/c/d/test.json ./`

Seems like I receive back a binary version of this file rather than a JSON. 
Downloading the file with NodeJS everything Is working fine.

May I have miss something?

**Comment by afranken** [comment]
@danieler1981 if no content type is given when an S3 object is uploaded, the backend automatically assigns `binary/octet-stream` as the content type.
I'm guessing that NodeJS applies some magic where it guesses the content-type from the file name.

Anyway, this issue is about a completely different problem, which seems to be resolved. 
Closing.
