### ISSUE TITLE
Garbage collection perhaps needed in case of crashing docker containers

### ISSUE THREAD

**Issue by AhtiAhde** [adobe/S3Mock#249]
I noticed that upon startup S3 Mock gives me strangely long steam of very fast stdout/err that takes forever to finish and it seemed to get longer every now and then.

I also noticed that my disk space was getting more and more full.

Whenever S3 Mock crashes, it keeps the files in the filesystem, even though same bucket would be created with exactly same files. So the crashing S3 Mock had been creeping my filesystem until I finally noticed it now (60GB).

If the files are kept upon crashes and I as a user should manually destroy the files instead of assuming that they are overriden as they would with normal shut down and rewrite process, I would like to get notified.

I occasionally destroy all docker images and containers and had been saved by this, but lately I had been working on a project where only malfunctioning container had been S3 Mock and I had thought that "one image can not consume that much memory", but it seems that S3 Mock has a kind of parasitic attitude when it crashes and it doesn't clean up the mess or hint the user to check out the mess.

A warning message about this extra garbage upon crashes would be highly appreciated!

**Comment by afranken** [comment]
@AhtiAhde thanks for reporting this.
I have proposed a change that deletes all files *on a regular shutdown*.
Unfortunately, there's no way to delete files if the process itself is not shut down in an orderly fashion, for instance if the Docker container crashes.
We also can't print out any warnings, since any shutdown hook we would register (both in the Java process or in Docker) would again need the system to shut down in an orderly fashion.

This is the same for any process by the way, not a limitation of the S3Mock or Docker.

**Comment by afranken** [comment]
@AhtiAhde you could, however, use a local file system to store the files like it's proposed in #200
Then you would be able to see residual data after crashes.
