### ISSUE TITLE
Move the custom banner to a custom location

### ISSUE THREAD

**Issue by mpaluchowski** [adobe/S3Mock#277]
Could you change the location of `banner.txt` to a different one, and configure it explicitly via `spring.banner.location`?

Currently it's placed in the classpath root, and when we include it in the test scope of another Spring Boot application, the S3Mock banner appears on all tests and calling `silent()` on the builder has no effect. (We don't use custom banners ourselves.)

Moving it to a different path should prevent the base application from loading it.

**Comment by afranken** [comment]
How do you instantiate the S3Mock?
#256 describes how to get rid of the logo. :)

**Comment by afranken** [comment]
Ah, sorry, I understand - the banner is picked up by *your* application.

**Comment by afranken** [comment]
Are you able to run Docker in your builds?

S3Mock 2.2.0 was just released that now includes support for [TestContainers](https://www.testcontainers.org/).
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.

Using S3MockApplication directly or through one of the unit test modules will always have the risk of breaking because of dependencies that are pulled in by the application that is being tested, and auto configration that is added through Spring Boot updates in the S3Mock.

Using Docker in your tests will insulate both applications dependencies and application life cycles.

**Comment by mpaluchowski** [comment]
We're making a conscious decision to avoid Docker in this case.

Do I understand correctly that S3Mock usage without Docker is discouraged?

**Comment by mpaluchowski** [comment]
Running S3Mock inside Docker will not solve the issue, because we still need to add `com.adobe.testing:s3mock` as a dependency in tests, so the `banner.txt` will become part of the test classpath.

**Comment by afranken** [comment]
> We're making a conscious decision to avoid Docker in this case.

May I ask why?

> Do I understand correctly that S3Mock usage without Docker is discouraged?

Yeah, I'd say it's discouraged if you're testing a Spring application.
The problem is that the class paths are always entangled during the unit tests if you start the S3Mock using the Java API.
Any dependency update in your application or in the S3Mock may break the startup of the other application, for example an auto configuration is suddenly triggered because new classes are on the class path.
Spring (Boot) is just not expecting two distinct Spring applications with different configurations to be started in the same classpath, and I doubt that this will change in the future.

We're thinking of replacing Spring Boot with Quarkus as a framework for the S3Mock, but I can't promise that this won't break your tests as well, as there are again different dependencies that may break the tested application...

> Running S3Mock inside Docker will not solve the issue, because we still need to add com.adobe.testing:s3mock as a dependency in tests, so banner.txt will become part of the test classpath.

why do you need the `com.adobe.testing:s3mock` dependency if you're using the TestContainers integration?
You should only need the S3 SDK. (see [base integration test](https://github.com/adobe/S3Mock/blob/main/testsupport/testcontainers/src/test/java/com/adobe/testing/s3mock/testcontainers/S3MockContainerTestBase.java) for the TestContainers module)

**Comment by mpaluchowski** [comment]
OK, I get your point.

**Comment by afranken** [comment]
@mpaluchowski be sure to give us feedback on the integration with the TestContainer, if you choose to use it :-)
