### ISSUE TITLE
Adding a dependency on S3Mock enables debug logging for org.apache.http and software.amazon

### ISSUE THREAD

**Issue by robd** [adobe/S3Mock#342]
When I add a gradle dependency on S3Mock, debug logging becomes enabled for calls made by my application code for `org.apache.http`, `software.amazon`. This occurs when I add the following to my `build.gradle.kts` (even if I don't make any code changes to use anything from S3Mock):

```
testImplementation("com.adobe.testing:s3mock:2.3.2")
```

I think this is to do with a transitive dependency on something in `org,springframework.boot`, because when I exclude this group from the S3Mock dependency the logging disappears. Note - this is before I make any code changes to call `S3MockApplication` and setting the `PROP_SILENT` to true doesn't help (the logging I see are is for calls made by my app, not by S3Mock).

Any idea how to stop spring from turning this logging on?

**Comment by robd** [comment]
After more investigation, this was because of the transitive dependency to `ch.qos.logback:logback-classic:1.2.7` from spring boot, and I fixed it by excluding that dependency in my `build.gradle.kts`:

```kts
testImplementation("com.adobe.testing:s3mock:2.3.2") {
  exclude(group="ch.qos.logback")
}
```

Is it possible / desirable to exclude this dependency within the S3Mock? Most people will want to configure their own logging provider I think.

**Comment by afranken** [comment]
Support for [TestContainers](https://www.testcontainers.org/) was added in S3Mock 2.2.0, a Docker container for general usage was added way before that.
If there is a possibility of running Docker during your build, I would highly suggest migrating to TestContainers.

Using `S3MockApplication` directly or through one of your unit test modules will always have the risk of breaking because of dependencies that are pulled in by the application that is being tested, and auto configuration / dependencies that are added through Spring Boot updates in the S3Mock.

Using Docker in your tests will insulate both applications dependencies and application life cycles.

**Comment by robd** [comment]
I'm not able to install Docker in my situation (locked down machines). Helpful to know that using`S3MockApplication` directly may break at any time - and now see that you have sent this reply on 10+ issues so apologies for retreading old ground. Would it be helpful to remove the instructions to use it programmatically way from the README? - happy to do a PR for this if that would help.

**Comment by afranken** [comment]
No worries - it's what maintainers are there for :)

You can still use the S3Mock programmatically, it's just impossible to separate your application's classpath from the S3Mock classpath if you directly start it in unit tests, and we can't guarantee stability over even patch releases because we need to keep up with dependency updates.

**Comment by AlJohri** [comment]
Looks like I just made a very similar comment here https://github.com/adobe/S3Mock/issues/141#issuecomment-1004366838

Thanks for patiently replying to each of them @afranken!

Totally understand that the dependencies change over time and we can't isolate the classpath when docker is not used, but I think my question still stands- is it possible to remove the logging dependencies in the pom.xml via an exclude?

Something like:

```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by AlJohri** [comment]
FWIW, I manually removed the following imports:

```
org.springframework.boot:spring-boot-starter-logging
org.apache.logging.log4j:log4j-to-slf4j
ch.qos.logback:logback-classic
ch.qos.logback:logback-core
```

And was able to add back in my desired logging import: `org.apache.logging.log4j:log4j-slf4j-impl`

and as long as I start the server with silent  = true:

```java
@BeforeAll
public static void setUp() {
    s3Mock = S3MockApplication.start(new HashMap<>(Map.of("silent", (Object) true)));
}

@AfterAll
public static void teardown() {
    s3Mock.stop();
}
```

everything seems to work smoothly without any version conflicts... so I guess it is safe to remove these dependencies? both from a library consumer perspective and perhaps even from this library's perspective?

please let me know if I'm missing something!

**Comment by afranken** [comment]
We need at least one logging backend (otherwise, S3Mock will not log anything), and Spring Boot uses logback by default.
Replacing it with log4j or some other logger ([slf4j simple](https://search.maven.org/artifact/org.slf4j/slf4j-simple/1.7.32/jar) for instance) may work

Removing those dependencies from the S3Mock entirely may break some other user's tests.

This is the reason why it's much simpler both from the provider's standpoint, and also the consumer's standpoint to run the mock in a Docker container - the S3Mock will run in a completely separate JVM and not interfere with your application as you test it.

The sad truth is that basically every dependency, public class and public method is part of the S3Mock's API if you use the JARs directly. Any changes made to the code could break any number of projects pulling in S3Mock java dependencies... :(

**Comment by afranken** [comment]
I'll close this, please reopen or open a new issue in case you have more questions.

**Comment by AlJohri** [comment]
>The sad truth is that basically every dependency, public class and public method is part of the S3Mock's API if you use the JARs directly.

Ah, that makes sense- totally understand that you can't remove the packages.

Since this seems to have come up in a few other issues, I initially thought you might be able to remove the packages from the main `S3Mock` library and add them back in for the docker/testcontainers submodule, but if it's part of the public API, I can understand that this may be depended upon.

Fortunately, it's easy enough for me to remove the dependencies when pulling S3Mock in so I think we're good to go here!
