### ISSUE TITLE
Alternative for S3MockApplication.getPort()

### ISSUE THREAD

**Issue by ginkel** [adobe/S3Mock#418]
Hi there,

version 2.4.x has deprecated the `S3MockApplication.getPort()` method. Which alternative that isn't deprecated do you recommend to determine the port of the S3 Endpoint URI from within JUnit 5? So far we used `URI.create("https://localhost:%s".formatted(s3MockApplication.getPort()))`.

Thanks,
Thilo

**Comment by afranken** [comment]
Thilo,
sorry, I should have added the deprecation notice description to the JavaDoc, and will do so soon. Thanks for pointing that out!

In general, using the S3Mock directly through it's Java API is now discouraged.

---------------

Rationale:

Starting and using the S3Mock directly (in a JUnit test) is and always will be problematic because the dependencies and the framework we use (Spring Boot) directly interferes with the classes / dependencies / framework you are using in your own application.

Unfortunately, any public class and method, and even the Java baseline is (unintentionally) part of the public API. 
Any customer could be using any number of methods, and I could be breaking any number of integrations with a simple refactoring.

I have heavily refactored the code base in the last couple of months and I'm far from done. 

For example:
The controller classes are too large by far, I'd like to split those up.
With the current way we persist binaries and metadata, it is hard to add additional features like ACLs or versioning, which people have asked about. I'll probably end up rewriting the whole FileStore.
Spring Framework 6 and Spring Boot 3 will be released later this year, raising their Java baseline to 17. Once I update, this will update the Java baseline of the plugin as well (which will almost definitely break a lot of customer projects, as any customer directly using the S3Mock would have to update to Java 17+ as well).
I am also toying with the idea of refactoring the whole thing into Kotlin (again, breaking a lot of direct integrations, although the binary code produced should be compatible to Java 8+).

---------------

The best way to insulate both the application under test and the S3Mock is by running two separate JVMs. This can easily be done by running the S3Mock in a Docker container, either by starting up the Docker container (e.g. through Maven or Gradle) before running the tests on your application, or by using [TestContainers](https://www.testcontainers.org/)

Cheers,
Arne
