### ISSUE TITLE
Setting port number for docker - how?

### ISSUE THREAD

**Issue by anowak-ct** [adobe/S3Mock#506]
How can I change the http port number used by the adobe/s3mock container from 9090 to some other port?

**Comment by afranken** [comment]
Hi!
Just like any Docker container, any port needs to be exported / mapped to a port on your machine.
See
https://github.com/adobe/S3Mock#build--run
for examples on how to run the container. (e.g. instead of setting `-p 9090:9090` set `-p 10000:9090`)

Also, if you want to change the port *inside* the container that's possible by setting environment variables on startup:
https://github.com/adobe/S3Mock#configuration

Cheers,
Arne

**Comment by afranken** [comment]
@anowak-ct I expect that your question is answered, so I'll close this issue. 
If there are more questions, just re-open this issue, or open a new one.
