### ISSUE TITLE
HeadBucket not supported

### ISSUE THREAD

**Issue by k2r79** [adobe/S3Mock#874]
Hello,

I've updated my project to use `s3mock:2.8.0` instead of `s3mock:2.2.3` and since I can't send a HEAD request to check a bucket.

My application returns the following message :

```
WARN 1 --- [qtp409598930-31] o.s.web.servlet.PageNotFound             : Request method 'HEAD' not supported
```

And when trying with `aws s3api --endpoint-url=http://localhost:9091/ head-bucket --bucket=myBucket` command, I get the following answer :

```
An error occurred (405) when calling the HeadBucket operation: Method Not Allowed
```

I checked the README and the method is marked as supported.

![image](https://user-images.githubusercontent.com/4272277/197554189-da76354a-8d94-4679-bf38-6fe193722aee.png)

Am I doing something wrong ? 😊

**Comment by afranken** [comment]
@k2r79 
I'll have to look into sending a better errormessage (it's generated by Spring).

The problem is that your bucket name contains an upper case letter. 
This is not allowed in AWS, and is now disallowed in S3Mock as well. Creating a bucket with an invalid name is disallowed as well.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
