### ISSUE TITLE
Store objects using normalized file names to allow special chars

### ISSUE THREAD

**Issue by agudian** [adobe/S3Mock#94]
The S3 API allows for special characters in the object keys.

We don't yet support all special chars and the character `/` is interpreted as a directory delimiter (S3 doesn't do that).

I propose that we store all objects using a UUID file name and map the original object key to the UUID in a map.

**Comment by afranken** [comment]
I did not realize that we had this issue, but with version 2.5.0, I refactored more or less the whole S3Mock core, and we now store Objects in UUID-folders instead of using the incoming `key` values.
With this change, I could get rid of many workarounds only needed to properly encode/decode the keys in order to make them usable for paths in Java / the file system. :)

This has now been implemented. 🎉
